[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# 指定大 app 分区表，支持大固件 OTA
board_build.partitions = min_spiffs.csv

# 正确引入 MQTT 客户端库与工业级 JSON 序列化库
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4